package com.example.gallery.media.remote.music

data class Album(
    val name: String = "",
    val id: Int = 0,
    val type: String = "",
    val size: Int = 0,
    val picId: Long = 0,
    val blurPicUrl: String = "",
    val companyId: Int = 0,
    val pic: Long = 0,
    val picUrl: String = "",
    val publishTime: Long = 0,
    val description: String = "",
    val tags: String = "",
    val company: String = "",
    val briefDesc: String = "",
    val artist: Artist = Artist(),
    val songs: List<Any> = listOf(),
    val alias: List<Any> = listOf(),
    val status: Int = 0,
    val copyrightId: Int = 0,
    val commentThreadId: String = "",
    val artists: List<ArtistXX> = listOf(),
    val subType: String = "",
    val transName: Any? = null,
    val onSale: Boolean = false,
    val mark: Int = 0,
    val gapless: Int = 0,
    val picId_str: String = ""
)